# Contract Repository & Lifecycle Management System
# Main Application Configuration
# Banque Populaire - Morocco

spring:
  application:
    name: contract-repository-system

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Database Configuration (will be overridden by profile-specific configs)
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Flyway Database Migration
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

  # Web Configuration
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  # Jackson JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Africa/Casablanca
    default-property-inclusion: non_null

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/contract-mgmt}

  # Mail Configuration (for notifications)
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Actuator Configuration
  actuator:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
        base-path: /actuator
    endpoint:
      health:
        show-details: when_authorized

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

# Logging Configuration
logging:
  level:
    com.bp.contractrepository: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# Application-Specific Configuration
app:
  name: Contract Repository System
  version: 1.0.0
  description: Enterprise contract management system for Banque Populaire

  # Security Configuration
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  # File Storage Configuration
  storage:
    documents:
      path: ${DOCUMENT_STORAGE_PATH:./storage/documents}
      max-file-size: 10485760  # 10MB in bytes
      allowed-extensions: pdf,doc,docx,xls,xlsx,txt,jpg,jpeg,png

  # Integration Configuration
  integration:
    core-banking:
      type: ${CORE_BANKING_TYPE:mock}  # t24, evolan, or mock
      timeout: 30000
      retry-attempts: 3
      circuit-breaker:
        failure-threshold: 5
        recovery-timeout: 60000

    t24:
      base-url: ${T24_BASE_URL:http://localhost:8081}
      client-id: ${T24_CLIENT_ID:contract-mgmt-service}
      client-secret: ${T24_CLIENT_SECRET:}

    evolan:
      base-url: ${EVOLAN_BASE_URL:http://localhost:8082}
      client-id: ${EVOLAN_CLIENT_ID:contract-mgmt-service}
      client-secret: ${EVOLAN_CLIENT_SECRET:}

    hr:
      base-url: ${HR_BASE_URL:http://localhost:8083}

  # Notification Configuration
  notification:
    email:
      enabled: ${EMAIL_NOTIFICATIONS_ENABLED:true}
      from: ${EMAIL_FROM:noreply@banquepopulaire.ma}
      templates:
        contract-expiry: classpath:templates/email/contract-expiry-reminder.html
        contract-created: classpath:templates/email/contract-created-notification.html

    reminder:
      default-days: 30,60,90
      batch-size: 100

  # Data Retention Configuration (Production Configurable)
  retention:
    contracts:
      default-years: ${CONTRACT_RETENTION_YEARS:7}
    documents:
      confidential-years: ${CONFIDENTIAL_DOC_RETENTION:10}
    audit:
      years: ${AUDIT_RETENTION_YEARS:10}

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
  health:
    diskspace:
      enabled: true
    db:
      enabled: true

# OpenAPI/Swagger Documentation
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: Contract Repository API
    description: Enterprise contract management system for Banque Populaire
    version: 1.0.0
    contact:
      name: Contract Management Team
      email: contract-mgmt@banquepopulaire.ma